### ISSUE TITLE
add project to Projects using Docile / Lexicon

### ISSUE THREAD

**Issue by peter1000** [joshday/AverageShiftedHistograms.jl#1]
hi,

Are you still using Docile/Lexicon for documentation. If so 
I would like to add your project to [Projects using Docile / Lexicon](https://github.com/MichaelHatherly/Docile.jl#projects-using-docile--lexicon)
if that is fine with you.

Thanks.

**Comment by joshday** [comment]
Absolutely.  Please do.

**Comment by peter1000** [comment]
Thanks
