### ISSUE TITLE
Dependency on UnicodePlots?

### ISSUE THREAD

**Issue by juliohm** [joshday/AverageShiftedHistograms.jl#14]
Could you please explain why it is needed? If it is an optional feature, could you please consider dropping the dependency?

**Comment by joshday** [comment]
It provides a prettier show method.  It's a lightweight dependency, but I would consider dropping it.  It's really nice for working in the REPL though.

**Comment by juliohm** [comment]
I checked their REQUIRE file, it is indeed super lightweight. I wonder how it is possible to implement plots in a terminal with just StatsBase.jl! Impressive. I will close the issue, not a big deal. :)

I am still digesting the idea of `show` with plots...
