### ISSUE TITLE
Code example in the docs not working

### ISSUE THREAD

**Issue by juliohm** [joshday/AverageShiftedHistograms.jl#16]
```julia
using AverageShiftedHistograms

y = randn(100_000)
o = ash(y, -5:.1:5)

type StepRangeLen has no field divisor
```

**Comment by joshday** [comment]
I haven't touched this package in a while, but I'm cleaning things up now.  Give me 20 minutes!

**Comment by joshday** [comment]
All is well on master.  Also, use ?ash for documentation.  I'm rewriting the gh-pages docs to reflect my changes.

**Comment by juliohm** [comment]
Beautiful, I am closing the issue. Looking forward for a new release.
