### ISSUE TITLE
Add pdf() implementation for 2D density

### ISSUE THREAD

**Issue by juliohm** [joshday/AverageShiftedHistograms.jl#17]
Could you please let me know when 2D density estimation is ready? I see that you are rewriting it.

Thanks again, I am looking forward to use your package in one of my GeoStats.jl solvers.

**Comment by joshday** [comment]
I'd like to do another iteration of docs and tests before putting out a release, but 2d estimation is on master.  Take a look at "latest" docs.

**Comment by juliohm** [comment]
Thank you @joshday, it is working perfectly. How to evaluate the density at a new location?

**Comment by joshday** [comment]
It's not implemented for bivariate (yet), only univariate:

```julia
julia> a = ash(randn(10000));

julia> pdf(a, .1)
0.37732226126422047
```

I'm in the middle of writing a dissertation so I probably won't get to that anytime soon, even though coding is a lot more fun.

**Comment by juliohm** [comment]
I am gonna start writing my thesis very soon too. I can fully appreciate the lack of time. :)

Just curious, how the density is evaluated in ASH? What is the interpolation strategy?

**Comment by joshday** [comment]
I just do linear interpolation between the density estimates in the adjacent bins of a new data point.  Since bins are narrow and ASH has already smoothed things, I don't think there's anything to be gained by doing something fancy.

**Comment by juliohm** [comment]
That sounds perfect, thanks.

**Comment by ParadaCarleton** [comment]
@joshday did this ever end up implemented? `pdf` doesn't seem to work.

**Comment by joshday** [comment]
Sorry to say I did not work on this and won't have any time to try it in the near future.
