### ISSUE TITLE
Smarter Plot Recipes

### ISSUE THREAD

**Issue by joshday** [joshday/AverageShiftedHistograms.jl#18]
Moving [discourse discussion](https://discourse.julialang.org/t/kernel-density-estimation-status/5928/26) here.  @piever

I like these two ideas.  Ideally,

- [x] Ash recipe would behave the same as the [KernedelDensity recipe](https://github.com/JuliaPlots/StatPlots.jl/blob/master/src/StatPlots.jl#L17) 
- [x] You could hide the histogram/sticks series

**Comment by joshday** [comment]
On master,  you can now do

```julia
a = ash(randn(1000))

plot(a)

plot(a; hist = false)
```

**Comment by piever** [comment]
Cool! For the 2D recipe to be the same as kernel density I think it's super easy, you should just remove the `seriestype --> :heatmap` line and then it would do the seriestype that you ask (possible choices being `surface`, `heatmap`, `contour` and `contourf`).

For the 1D case, I have a minor suggestion as to how to write the code: if you have multiple series, they can be written using the `@series` macro (see [here](https://github.com/JuliaPlots/StatPlots.jl/blob/master/src/marginalhist.jl#L18) for an example). Then you would just add a `if hist` before the second `@series`.

I'm curious whether there is some equivalent of your `hist` keyword for kernel density. Would it just mean showing the normalized histogram on top of the density plot? If that's what you are doing maybe it could be added to the kernel density as well (I'm not sure showing it should be the default though). Why do you choose to show the histogram density with sticks and not bars? (sorry if it's an ignorant question, I learned about this estimation technique today...)

**Comment by joshday** [comment]
Thanks for the pointer!  I'll check out `@series`.  I'm not sure if there is a `hist` equivalent for normal KDE.  I used sticks to help show how fine the partition is for the histogram, but I'm open to changes.

**Comment by joshday** [comment]
Updates now in metdata.
