### ISSUE TITLE
Can UnicodePlots.jl version be updated?

### ISSUE THREAD

**Issue by BoundaryValueProblems** [joshday/AverageShiftedHistograms.jl#36]
Hello.
The current version of `AverageShiftedHistogram.jl`'s Project.toml says:
```
[compat]
UnicodePlots = "1.1"
```
Because of this the version of `UnicodePlots.jl` on my computer is v1.14.0.
This version is quite obsolete: the current version of `UnicodePlots.jl` is v2.4.4. 
If I want to use the latest version of `Plots.jl` v1.22.1 and the `AverageShiftedHistograms.jl` together, I get the following warning if I use them under my vscode session as discussed in the thread https://github.com/JuliaPlots/Plots.jl/issues/3831 .
I am wondering whether the `Project.toml` can be upgraded so that it accepts the more recent versions of `UnicodePlots.jl`. Thanks a lot for your help!!

**Comment by joshday** [comment]
Thanks for letting me know! I think CompatHelper must've stopped running.  I'll update the versions for all the deps.

**Comment by BoundaryValueProblems** [comment]
Thanks a lot for taking care of this!!
