### ISSUE TITLE
Add Distributions.jl Dependency

### ISSUE THREAD

**Issue by ParadaCarleton** [joshday/AverageShiftedHistograms.jl#44]
Distributions.jl is a more widely-used interface for working with distributions with more users. Making ASH histograms a subtype of Distributions.jl's density would substantially improve how much of the ecosystem can work with ASH.

Prior to 1.9, I think avoiding the Distributions.jl dependency was a good idea, but now with native code caching, the extra compile time is negligible. In addition, adding Distributions.jl would let the code be simplified substantially in some parts by taking advantage of existing methods from Distributions.jl.

Distributions.jl would also allow for a wider variety of kernels (any Distribution), as well as better density estimates in the tails. (A generalized Pareto Distribution can be fitted to the most extreme observations and used to predict outside the range of observations, rather than taking the ASH estimate directly.)

**Comment by joshday** [comment]
Distributions (and indirectly, it's 56 dependencies!) is much too heavy to add here.  

You can already use any kernel function you want.  I'm not sure what you're describing with generalized Pareto.

**Comment by ParadaCarleton** [comment]
> Distributions (and indirectly, its 50-something dependencies!) is much too heavy to add here.

Right, so Distributions.jl+indirect dependencies is quite heavy, but the main thing is that almost all of those indirect dependencies are dependencies for ASH.jl alreay. The remaining 10-ish dependencies are lightweight and widely used across the statistics ecosystem, enough so that if someone loads any other packages besides ASH, they're almost guaranteed to pick up most of the remaining 10.
![image](https://github.com/joshday/AverageShiftedHistograms.jl/assets/71727937/20bf7b58-8f46-43df-b5f3-4228abd10f5c)

**Comment by ParadaCarleton** [comment]
Probably the bulk of the marginal weight comes from Plots.jl and UnicodePlots.jl, which add substantially more overhead than Distributions.jl and aren't part of most users' statistical analysis toolbox (lots of people are using Makie, Gadfly, VegaLite, etc. instead).

This is fairly visible in the compile times, where Distributions.jl would end up being about 15% of the compile time if added.
![image](https://github.com/joshday/AverageShiftedHistograms.jl/assets/71727937/1ea24197-bf3e-457e-b9d2-5529c279ee10)

**Comment by joshday** [comment]
1. I don't see a benefit.
2. Plots.jl isn't a dependency of either package.

**Comment by ParadaCarleton** [comment]
> Plots.jl isn't a dependency of either package.

Sorry, name made me think UnicodePlots.jl depended on Plots.jl.

> I don't see a benefit.

Being able to overload `logpdf`, `cdf`, etc. and make `ASH <: Distribution` so it can automatically have all the Distribution functions defined for it (e.g. all summary statistics, including weirder ones like divergences).
