### ISSUE TITLE
Weighted ASH method broken

### ISSUE THREAD

**Issue by ParadaCarleton** [joshday/AverageShiftedHistograms.jl#49]
@itsdebartha 
```julia
julia> import AverageShiftedHistograms as avsh

julia> import StatsBase as sb

julia> avsh.ash(randn(100), sb.pweights(rand(100)))

ERROR: DimensionMismatch: Length of weights should be same as the length of the range
Stacktrace:
  [1] _weightedhistogram!
    @ AverageShiftedHistograms ~/.julia/packages/AverageShiftedHistograms/3v6jW/src/univariate.jl:48 [inlined]
  [2] ash(x::Vector{…}, weight::StatsBase.ProbabilityWeights{…}; nbin::Int64, rng::StepRangeLen{…}, m::Int64, kernel::Function)
    @ AverageShiftedHistograms ~/.julia/packages/AverageShiftedHistograms/3v6jW/src/univariate.jl:127
  [3] ash(x::Vector{Float64}, weight::StatsBase.ProbabilityWeights{Float64, Float64, Vector{Float64}})
    @ AverageShiftedHistograms ~/.julia/packages/AverageShiftedHistograms/3v6jW/src/univariate.jl:125
```

**Comment by itsdebartha** [comment]
This `DimensionMismatch` is by design. I have implemented it so that the weights are given to each of the bins of the histogram, rather than the individual values.
This is so that a single value cannot have more than one weight, but the weight of the bin that the value is in

**Comment by ParadaCarleton** [comment]
> This `DimensionMismatch` is by design. I have implemented it so that the weights are given to each of the bins of the histogram, rather than the individual values.

I'm not sure what you mean here. Each individual value should have a weight, not a bin. It doesn't make sense to assign weights to bins; observations have weights, not bins.

**Comment by joshday** [comment]
I've reverted the weighted ASH PR.  I don't have time to implement it, but would review another PR for it.
